server:
  port: 8015
spring:
  application:
    name: order-service-sentinel
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
stock-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.ideapro.order.rule.MyRule
ribbon:
  eager-load:
    #hungry load方式
    enabled: true
    #more than one services, use comma separated
    clients: stock-service
  NFLoadBalancerRuleClassName: com.ideapro.order.rule.MyRule

logging:
  level:
    com.ideapro.order.feign: error
#设置feign的日志级别
feign:
  client:
    config:
      stock-service:
        loggerLevel: FULL